spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: local

  flyway:
    enabled: false

  jpa:
   hibernate:
     ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: prod

  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
